zookeeperUrls: ip-10-228-101-92.ingest.cdp.internal:2181/kafka
refreshSeconds: 60
jaasConf: /home/centos/jaas.conf
kerberos: true 
kafkaBroker:
 - ip-10-228-101-92.ingest.cdp.internal
 - ip-10-228-101-171.ingest.cdp.internal
 - ip-10-228-101-158.ingest.cdp.internal 
kafkaPort: 6667
commonZkRoot: /

server:
  applicationConnectors:
    - type: http
      port: 8989
      maxRequestHeaderSize: 32KiB
      maxResponseHeaderSize: 32KiB
